add singleDB config
prest/prest pull request #584
Opened 2021-08-16 15:25 UTC by arxdsilva

* avoids db change on single db config
* avoids malformated queries to break subsequent http calls

https://github.com/prest/prest/issues/497
https://github.com/prest/prest/issues/578

2021-08-16 16:31 UTC, avelino commented
have you seen this proposal (pr) #583 ?

2021-08-16 17:21 UTC, arxdsilva commented
> have you seen this proposal (pr) #583 ?

yes, dont know if we'll ever get a perfect fit without redesigning a few things, but decided to contribute this as it doesnt change any interface signature and allows us to give users a not invasive answer to a problem that we have now.

2021-08-16 17:36 UTC, avelino requested changes
I agree with the proposed change (for not changing signature), can you write test and doc?

2021-08-23 01:32 UTC, arxdsilva commented
@avelino I've added the docs and tests, just let me know If you feel that any more docs may be needed or tests.

2021-08-23 11:23 UTC, merged