Add ECDSA/RSA-based JWT token support
prest/prest pull request #642
Opened 2021-12-17 16:52 UTC by korc

Implemented RSA and ECDSA type of JWT key (RS* and ES* algo) checking.
Login/generation part not included.

## Testing code

Tested using `certtool` from [GnuTLS](https://gnutls.org),  [jwt](https://github.com/golang-jwt/jwt/tree/main/cmd/jwt) and [onefile-websrv](https://github.com/korc/onefile-websrv).

###  Generation of keys
```
certtool -p --outfile rsa.key
# ECDSA keys are considerably smaller
certtool -p --outfile ecdsa.key --ecdsa
```

### Setting public keys in `prest.toml`
```
certtool --pubkey-info --load-privkey ecdsa.key
```
Copy-paste PEM data between and including BEGIN and END lines as multi-line string value for `jwt.key` using `"""` syntax in `prest.toml` like this:
```
[jwt]
algo = "ES256"
key = """
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEiU5COUED4Jtml5qd6S48D1828jvn
NPO+ZSY6VA7tBXmaGCCFP0sIUDgYRhCu2qYj2jeq3dbpMlZvn7jDgpPzMQ==
-----END PUBLIC KEY-----
"""
```

### Generating tokens with `jwt`

```
token="$(jwt -sign + -key rsa.key -alg RS256)"
curl -H "Authorization: Bearer $token" localhost:3000/databases
```

### Generating JWT token on-fly with `onefile-websrv`

_Should go without saying that for real-world use, this server should be secured with additional configuration._

```
onefile-websrv -map "/rsa=jwt:{alg=RS256,exp=ts:+1h}file:rsa.key" -map "/ecdsa=jwt:{alg=ES256,exp=ts:+1h}file:ecdsa.key" -map "/hs=jwt:{alg=HS256,exp=ts:+1h}s3cr3t" -listen 127.0.0.1:3001
# for ECDSA keys
curl -H "Authorization: Bearer $(curl -s localhost:3001/ecdsa)" http://localhost:3000/databases
# for RSA kes
curl -H "Authorization: Bearer $(curl -s localhost:3001/rsa)" http://localhost:3000/databases
# for shared secrets
curl -H "Authorization: Bearer $(curl -s localhost:3001/hs)" http://localhost:3000/databases
```

2021-12-17 16:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prest/prest?pullRequest=642) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/prest/prest?pullRequest=642) before we can accept your contribution.<br/><hr/>**Lauri Korts-Pärn** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prest/prest?pullRequest=642) it.</sub>

2021-12-17 19:29 UTC, korc commented
After submitting, I noticed there was actually already pull request #552 ... My approach does not have slice panic problem, because I use strings.HasPrefix, and is probably slightly faster, because it parses the keys at startup, not  at each request. IMHO easier to catch problems with key setup.
It doesn't use `jwt.Parse*PEM` functions though, instead going to directly parsing pem, very much like jwt.Parse*PEM do, and also support private keys.
Which approach would you prefer?

2021-12-23 08:45 UTC, avelino requested changes

2021-12-23 08:45 UTC, avelino commented on middlewares/middlewares.go
>  func JwtMiddleware(key string, algo string) negroni.Handler {
We changed the jwt library (for one that was not archived), you can update your contribution with the `main` branch

**sorry**
ref: #635

2022-01-05 10:06 UTC, closed without merging