[experimental/POC] router - add QueryCtx to avoid query collision
prest/prest pull request #713
Opened 2022-08-10 21:22 UTC by arxdsilva

This allows the `GetTablesByDatabaseAndSchema` route to use on query only the requested DB, avoiding multiple requests collision. By this we:

1. extends current interface, allowing usage of current one
2. doesnt break old users
3. allow setting custom query timeouts

todo:
1. make usage of DB pool a standard

2022-08-10 23:11 UTC, avelino commented
Oh my good!

I am very very happy with your proposal 🎉

2022-08-12 14:23 UTC, DiegoSantosWS requested changes
I made some comments.

2022-08-12 14:23 UTC, DiegoSantosWS commented on adapters/postgres/postgres.go
> +	db, err := connection.GetFromPool(ctx.Value("db_name").(string))
Before o use the value in context check if exists the value... 

If for some reason the return of `ctx.Value("db_name").(string)` is empty?

2022-08-12 14:23 UTC, DiegoSantosWS commented on controllers/tables.go
> +	ctx := context.WithValue(r.Context(), "db_name", database)
Remove this line from here, and add place it closer to where it's used

2022-08-12 14:23 UTC, DiegoSantosWS commented on controllers/tables.go
> +	sc := config.PrestConf.Adapter.QueryCtx(ctx, sqlSchemaTables, valuesAux...)
```suggestion
    // set db name on ctx
	ctx := context.WithValue(r.Context(), "db_name", database)
	// send ctx to query the proper DB
	sc := config.PrestConf.Adapter.QueryCtx(ctx, sqlSchemaTables, valuesAux...)
```

2022-08-13 21:30 UTC, arxdsilva commented
local testing results:
![image](https://user-images.githubusercontent.com/9372503/184511263-6501d2e6-4867-4c47-86cc-fdc4aa531fa3.png)

![image](https://user-images.githubusercontent.com/9372503/184511275-c6a385a6-0aff-4dfc-bfa2-56658fc7d917.png)

query on not existant db:

![image](https://user-images.githubusercontent.com/9372503/184511297-e160ed36-e918-4789-974e-f3f46c2221ff.png)

```
[negroni] 2022-08-13T18:26:54-03:00 | 200 |      30.278041ms | localhost:6000 | GET /prest/public
[negroni] 2022-08-13T18:28:23-03:00 | 400 |      190.083µs | localhost:6000 | GET /newDB/public
```

config file used:

```toml
migrations = "./migrations"

debug = true

[http]
port = 6000

[jwt]
key = "secret"
algo = "HS256"

[auth]
enabled = false
type = "body"
encrypt = "MD5"
table = "prest_users"
username = "username"
password = "password"

[pg]
host = "127.0.0.1"
user = "prest"
pass = "prest"
port = 5432
database = "prest"
single = true

[ssl]
mode = "disable"
sslcert = "./PATH"
sslkey = "./PATH"
sslrootcert = "./PATH"

2022-08-25 00:29 UTC, DiegoSantosWS approved these changes

2022-08-25 18:01 UTC, arxdsilva commented
thanks for reviewing @DiegoSantosWS , what do you think about these router changes? I think we should take some decision about it

https://github.com/prest/prest/pull/713/files#diff-c399d26e7f23b713ce01946ac9e0e6f1fc94d692e8a086180191901da91b6964R27-R42

2022-10-16 18:17 UTC, merged

2022-10-16 19:13 UTC, avelino commented
🚀