Change port 6000 mentions to port 3000
prest/prest pull request #728
Opened 2022-10-28 14:03 UTC by vmesel

As a way to enable a better user experience (due to a fact related on #727), I've set all ports over the code to 3000, maintaining the references from the previous commits and documentation.

2022-10-28 18:05 UTC, arxdsilva approved these changes

2022-10-28 18:06 UTC, arxdsilva requested changes
seams like your branch is dirty, could you rebase?

2022-10-28 19:11 UTC, vmesel commented
I'm not sure if I did this correctly. How can I check if its correctly done? I've ran `git rebase origin/main`

2022-10-28 22:36 UTC, arxdsilva approved these changes

2022-10-30 02:47 UTC, vmesel commented
@arxdsilva can you merge it?

2022-10-31 11:29 UTC, merged