test: use `T.Setenv` to set env vars in tests
prest/prest pull request #755
Opened 2022-12-29 14:44 UTC by Juneezee

This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.

This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.

Reference: https://pkg.go.dev/testing#T.Setenv

```go
func TestFoo(t *testing.T) {
	// before
	os.Setenv(key, "new value")
	defer os.Unsetenv(key)
	
	// after
	t.Setenv(key, "new value")
}
```

2022-12-29 14:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prest/prest?pullRequest=755) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/prest/prest?pullRequest=755) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prest/prest?pullRequest=755) it.</sub>

2023-01-05 11:41 UTC, vmesel requested changes

2023-01-05 12:02 UTC, Juneezee commented on config/config_test.go
> +	t.Setenv("PREST_CONF", "../testdata/prest.toml")
We don't have any `init()` functions defined in the `config` package

2023-01-05 13:13 UTC, vmesel approved these changes

2023-01-05 13:13 UTC, vmesel commented
LGTM @avelino @arxdsilva

2023-01-05 18:09 UTC, merged

2023-01-05 18:09 UTC, arxdsilva commented
Thanks for your contribution!

2023-01-05 18:18 UTC, avelino commented
thanks @Juneezee, but sorry for the delay in the review