test(samples): added postman sample to start the regression tests
prest/prest pull request #789
Opened 2023-03-24 00:28 UTC by ktfth

added samples to help automate regression tests
added instructions on own readme of the sample and the main readme added the usage of newman a cli tool from nodejs ecosystem

2023-03-24 00:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prest/prest?pullRequest=789) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/prest/prest?pullRequest=789) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prest/prest?pullRequest=789) it.</sub>

2023-03-24 11:13 UTC, avelino requested changes

2023-03-24 11:13 UTC, avelino commented on samples/README.md
This page could be inside the documentation, I don't think it is good to have readme in sub folder, it having to be forgotten to be updated in the future

2023-03-24 12:37 UTC, ktfth commented on samples/README.md
I can put the information on doc, but you see the possibility to maintain the collection and use as part of a regression test to be used on the process of CI/CD to guarantee the actual working state of the project?

2023-03-26 19:23 UTC, ktfth commented on samples/README.md
@avelino any considerations about that? Makes sense to start this kind of test to maintain the compatibility across new versions?

2023-03-26 19:57 UTC, avelino commented
@ktfth remember to sign the CLA please

2023-04-07 23:59 UTC, avelino requested changes

2023-04-07 23:59 UTC, avelino commented on samples/README.md
This readme is not needed, the same content is in the documentation

2023-04-08 23:34 UTC, avelino approved these changes
LGTM

2023-04-09 11:33 UTC, merged

2023-04-09 11:34 UTC, arxdsilva commented
Thanks @ktfth !