issue_783
prest/prest pull request #793
Opened 2023-04-03 19:48 UTC by Listener430

Added expired\notbefore validation for token claims for issue_783

2023-04-03 23:20 UTC, arxdsilva commented
Please provide tests for the new function and middleware.

2023-04-03 23:54 UTC, avelino requested changes
Can you write test to validate the implementation?

2023-04-06 15:35 UTC, avelino approved these changes
LGTM

2023-04-06 16:03 UTC, arxdsilva requested changes

2023-04-06 16:03 UTC, arxdsilva commented on middlewares/middlewares_test.go
> +	if err != nil {
Please use require here too

2023-04-06 16:03 UTC, arxdsilva commented on middlewares/middlewares_test.go
> +	bearer, _ := jwt.Signed(sig).Claims(cl).CompactSerialize()
Don't forget to check here too with require

2023-04-06 16:03 UTC, arxdsilva commented on middlewares/middlewares_test.go
> +	if err != nil {
Same here about require

2023-04-06 16:03 UTC, arxdsilva commented on middlewares/middlewares_test.go
> +	bearer, _ := jwt.Signed(sig).Claims(cl).CompactSerialize()
Same here about checking the error

2023-04-06 18:17 UTC, arxdsilva approved these changes
We'll approve and adjust later, thanks!

2023-04-06 18:18 UTC, merged